<?php
/**
 * CoreFlux Web Installer (one-click first-time setup)
 *
 * Visit: https://<your-app>/install.php
 *
 *   - Login as master_admin (uses existing CoreFlux session)
 *   - Paste OpenAI API key
 *   - Click Install
 *
 * Does, in order:
 *   1. Auto-generates COREFLUX_DATA_KEY (32 random bytes, base64)
 *   2. Writes core/config.local.php with both secrets
 *   3. Runs all pending DB migrations
 *   4. Runs the post-deploy smoke test
 *   5. Shows the result
 *
 * Self-disables once core/config.local.php exists & contains real values
 * (so this URL is dormant after first use). Re-enable by deleting that file.
 */

declare(strict_types=1);

require_once __DIR__ . '/core/config.php';
require_once __DIR__ . '/core/auth.php';
require_once __DIR__ . '/core/admin_gate.php';
require_once __DIR__ . '/core/installer_helpers.php';

$user = requireAdminForOps('install');

initSession();

$localCfg = __DIR__ . '/core/config.local.php';
if (file_exists($localCfg)) require_once $localCfg;

$alreadyInstalled = defined('COREFLUX_DATA_KEY')
    && COREFLUX_DATA_KEY
    && COREFLUX_DATA_KEY !== 'REPLACE_ME_WITH_BASE64_32_BYTES'
    && defined('OPENAI_API_KEY')
    && OPENAI_API_KEY
    && OPENAI_API_KEY !== 'sk-proj-REPLACE_ME';

// ---- Auth gate ----
// Already enforced above by requireAdminForOps('install'). $user is set.

// ---- Handle install POST ----
$result = null;
$error  = null;
if (!$alreadyInstalled && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $openaiKey = trim($_POST['openai_key'] ?? '');
    if ($openaiKey === '' || !preg_match('/^sk-[A-Za-z0-9_\-]+$/', $openaiKey)) {
        $error = "That doesn't look like an OpenAI API key. It should start with 'sk-' and contain only letters, numbers, hyphens, and underscores.";
    } else {
        try {
            $result = installCoreflux($openaiKey);
        } catch (Throwable $e) {
            $error = "Install failed: " . $e->getMessage();
        }
    }
}

/**
 * Run the install steps. Throws on any failure.
 * Returns: ['data_key' => '...', 'migrations' => [...], 'smoke' => [...]]
 */
function installCoreflux(string $openaiKey): array {
    $localCfg = __DIR__ . '/core/config.local.php';

    // 1. Generate data key
    $dataKey = base64_encode(random_bytes(32));

    // 2. Write config.local.php atomically
    $body = "<?php\n"
          . "// Auto-generated by /install.php on " . date('c') . ".\n"
          . "// COREFLUX_DATA_KEY encrypts SSN + bank details. NEVER change once data is encrypted.\n"
          . "define('COREFLUX_DATA_KEY', " . var_export($dataKey, true) . ");\n"
          . "define('OPENAI_API_KEY',    " . var_export($openaiKey, true) . ");\n";

    $tmp = $localCfg . '.tmp.' . bin2hex(random_bytes(4));
    if (file_put_contents($tmp, $body) === false) throw new RuntimeException("could not write $tmp (check folder permissions)");
    if (!rename($tmp, $localCfg)) {
        @unlink($tmp);
        throw new RuntimeException("could not move config into place ($localCfg)");
    }
    @chmod($localCfg, 0640);

    // 3. Run migrations + smoke test (shared with update.php)
    return [
        'data_key'   => $dataKey,
        'migrations' => runMigrationsInProcess(),
        'smoke'      => runSmokeInProcess($localCfg),
    ];
}

function h(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CoreFlux — Install</title>
<style>
  * { box-sizing: border-box; }
  body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, system-ui, sans-serif;
         color: #1c1f26; background: #f6f7fb; margin: 0; padding: 40px 20px; }
  .wrap { max-width: 640px; margin: 0 auto; background: #fff; border: 1px solid #e3e6ec;
          border-radius: 12px; padding: 32px; box-shadow: 0 4px 20px rgba(0,0,0,.04); }
  h1 { margin: 0 0 4px 0; font-size: 22px; }
  .muted { color: #6b7280; font-size: 13px; }
  label { display: block; font-weight: 600; margin: 20px 0 6px; }
  input[type="text"], input[type="password"] {
    width: 100%; padding: 10px 12px; border: 1px solid #d2d6de; border-radius: 6px;
    font: inherit; color: inherit;
  }
  .btn { display: inline-block; padding: 10px 18px; border-radius: 6px; border: 0;
         background: #5a6cff; color: #fff; font-weight: 600; cursor: pointer; font: inherit; }
  .btn:hover { background: #4859d6; }
  .btn--ghost { background: #fff; color: #1c1f26; border: 1px solid #d2d6de; }
  .alert { padding: 10px 14px; border-radius: 6px; margin: 16px 0; font-size: 13px; }
  .alert--err  { background: #fdf2f2; color: #9a2727; border: 1px solid #f3c0c0; }
  .alert--ok   { background: #f1faf3; color: #2c6e4a; border: 1px solid #b6d8c2; }
  .row { display: flex; align-items: center; gap: 8px; padding: 6px 0; font-size: 13px; }
  .row .tick { width: 18px; display: inline-block; }
  .row.ok .tick { color: #2ea46a; } .row.no .tick { color: #c94040; }
  pre { background: #0f111a; color: #e6e7ee; padding: 12px; border-radius: 6px;
        font-size: 12px; overflow-x: auto; }
  hr { border: 0; border-top: 1px solid #eef0f4; margin: 24px 0; }
  code { background: #eef0f4; padding: 1px 6px; border-radius: 4px; font-size: 12px; }
  details { margin-top: 8px; }
  details summary { cursor: pointer; color: #5a6cff; }
</style>
</head>
<body>
<div class="wrap">
  <h1>CoreFlux Setup</h1>
  <p class="muted">Logged in as <strong><?= h($user['email'] ?? 'admin') ?></strong></p>

  <?php if ($alreadyInstalled): ?>
    <div class="alert alert--ok">CoreFlux is already configured on this server.</div>
    <p>To re-run setup, delete <code>core/config.local.php</code> and reload this page.</p>
    <p style="margin-top:24px;">
      <a class="btn" href="/spa.php">Open the app</a>
      <a class="btn btn--ghost" href="/update.php">Run an update</a>
    </p>

  <?php elseif ($result): ?>
    <div class="alert alert--ok">Setup complete.</div>

    <h3 style="margin-top:24px;">Database migrations</h3>
    <?php foreach ($result['migrations'] as $m): ?>
      <div class="row ok"><span class="tick">✓</span> <code><?= h($m['file']) ?></code> — <?= h($m['status']) ?></div>
    <?php endforeach; ?>

    <h3 style="margin-top:24px;">Smoke test</h3>
    <?php foreach ($result['smoke'] as $c): ?>
      <div class="row <?= $c['ok'] ? 'ok' : 'no' ?>">
        <span class="tick"><?= $c['ok'] ? '✓' : '✗' ?></span>
        <strong><?= h($c['check']) ?></strong>
        <?php if (!empty($c['detail'])): ?> — <span class="muted"><?= h($c['detail']) ?></span><?php endif; ?>
      </div>
    <?php endforeach; ?>

    <details>
      <summary>Save this for your records (encryption key)</summary>
      <pre>COREFLUX_DATA_KEY = <?= h($result['data_key']) ?></pre>
      <p class="muted">Stored on this server in <code>core/config.local.php</code>. Keep a backup in your password manager. Changing it later orphans existing encrypted data.</p>
    </details>

    <hr>
    <p>
      <a class="btn" href="/spa.php">Open the app</a>
      <a class="btn btn--ghost" href="/diagnostics.php">Diagnostics</a>
    </p>

  <?php else: ?>
    <p>Two things needed and you're done:</p>
    <ol class="muted" style="line-height:1.8;">
      <li>Your OpenAI API key (we'll store it on this server only)</li>
      <li>One click — we'll auto-generate the encryption key, write the config, run migrations, and verify everything</li>
    </ol>

    <?php if ($error): ?><div class="alert alert--err"><?= h($error) ?></div><?php endif; ?>

    <form method="post" autocomplete="off" data-testid="install-form">
      <label for="openai_key">OpenAI API key</label>
      <input type="text" id="openai_key" name="openai_key" placeholder="sk-proj-..." required
             pattern="^sk-[A-Za-z0-9_\-]+$" data-testid="install-openai-key">
      <p class="muted">From <a href="https://platform.openai.com/api-keys" target="_blank">platform.openai.com → API keys</a>.
        Used by core/ai_service.php only; never sent to the browser after this.</p>

      <p style="margin-top:24px;">
        <button class="btn" type="submit" data-testid="install-submit">Install CoreFlux</button>
      </p>
    </form>
  <?php endif; ?>
</div>
</body>
</html>
