-- 108_ap_invoice_extractions_and_cash_forecast.sql
--
-- Slice E (final) — AP Invoice Review + 13-Week Cash Forecast tables.
--
-- Spec §11 ("AP Agent" + "Cash Agent") + scan §"Phase 5":
--
--   ap_invoice_extraction_runs
--     One row per AI extraction attempt against an uploaded invoice
--     PDF/image. Tracks the source, the AI-proposed payload, the
--     duplicate-check verdict, the linked draft bill (if any), the
--     promote-to-bill outcome.  Status flow:
--       pending → extracted → drafted → posted
--                          ↘ duplicate
--                          ↘ failed
--
--   cash_forecast_runs
--     One row per 13-week (or N-week) cash forecast generated by the
--     coreflux.run_cash_forecast tool.  Stores the JSON-encoded
--     bucket array so the dashboard can render the forecast without
--     re-computing.  Starting / ending balance + weeks_count surface
--     in the list view.
--
-- Idempotent. MySQL 5.7+. utf8mb4_unicode_ci.

CREATE TABLE IF NOT EXISTS ap_invoice_extraction_runs (
    id                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id              BIGINT UNSIGNED NOT NULL,
    sub_tenant_id          BIGINT UNSIGNED NULL,
    source_storage_uri     VARCHAR(500) NULL,         -- s3://… / coreflux://… pointer to the uploaded artifact
    source_filename        VARCHAR(255) NULL,
    source_mime_type       VARCHAR(80) NULL,
    source_artifact_id     CHAR(36) NULL,             -- artifact_objects.id of the source PDF (Slice A)
    -- Lifecycle.
    status                 ENUM('pending','extracted','duplicate','drafted','posted','failed') NOT NULL DEFAULT 'pending',
    error_message          VARCHAR(1000) NULL,
    -- Extraction output.
    extracted_payload_json LONGTEXT NULL,             -- {vendor_name, bill_number, bill_date, due_date, total, currency, lines[]}
    confidence             DECIMAL(4,3) NULL,
    -- Duplicate check.
    duplicate_check_status ENUM('not_run','no_match','match_exact','match_likely') NOT NULL DEFAULT 'not_run',
    duplicate_bill_id      BIGINT UNSIGNED NULL,      -- ap_bills.id of the matching row when status != no_match
    duplicate_reason       VARCHAR(255) NULL,
    -- Promotion to a real AP bill.
    draft_bill_id          BIGINT UNSIGNED NULL,      -- ap_bills.id of the draft
    posted_bill_id         BIGINT UNSIGNED NULL,      -- ap_bills.id after status=posted
    -- AI provenance.
    ai_run_id              CHAR(36) NULL,             -- ai_tool_invocations.id of the extract call
    created_by_user_id     BIGINT UNSIGNED NULL,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    KEY ix_ap_extract_tenant_status (tenant_id, status, id),
    KEY ix_ap_extract_tenant_dup    (tenant_id, duplicate_check_status, id),
    KEY ix_ap_extract_draft_bill    (draft_bill_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cash_forecast_runs (
    id                       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id                BIGINT UNSIGNED NOT NULL,
    sub_tenant_id            BIGINT UNSIGNED NULL,
    -- What was forecasted.
    weeks_count              INT UNSIGNED NOT NULL DEFAULT 13,
    starting_at              DATE NOT NULL,
    currency                 CHAR(3) NOT NULL DEFAULT 'USD',
    -- Cash position snapshot at run time (cents-safe).
    starting_balance_cents   BIGINT NOT NULL DEFAULT 0,
    ending_balance_cents     BIGINT NOT NULL DEFAULT 0,
    min_week_balance_cents   BIGINT NULL,             -- weekly low — flag for shortfall alerts
    -- Forecast payload.
    -- JSON shape: [{week_no, week_start, week_end,
    --              opening_balance_cents, ap_outflow_cents,
    --              ar_inflow_cents, payroll_outflow_cents,
    --              other_outflow_cents, closing_balance_cents,
    --              notes}]
    forecast_payload_json    LONGTEXT NOT NULL,
    -- AI provenance + artifact wire-in (Slice A).
    artifact_id              CHAR(36) NULL,
    ai_run_id                CHAR(36) NULL,
    created_by_user_id       BIGINT UNSIGNED NULL,
    created_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    KEY ix_cash_forecast_tenant     (tenant_id, id),
    KEY ix_cash_forecast_starting   (tenant_id, starting_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
