name: Deploy public_html to Cloudways via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false

      - name: Set deploy target to webroot
        run: echo "DEPLOY_TARGET=${{ secrets.CW_REMOTE_PATH }}/public_html" >> $GITHUB_ENV

      - name: Copy files with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CW_SSH_HOST }}
          username: ${{ secrets.CW_SSH_USER }}
          key: ${{ secrets.CW_SSH_KEY }}
          port: ${{ secrets.CW_SSH_PORT }}
          source: "public_html/*"
          target: ${{ env.DEPLOY_TARGET }}
          overwrite: true
